arm_keyboard_teleop:
  ros__parameters:
    joint_names: [slider, shoulder_1, elbow_1]
    slider_step: 0.005
    shoulder_step: 0.03
    elbow_step: 0.03
    slider_limits: [-0.25, 0.0]
    shoulder_limits: [-3.14159, 3.14159]
    elbow_limits: [-3.14159, 3.14159]
    slider_vel: 0.04
    shoulder_vel: 0.53
    elbow_vel: 0.53
    publish_rate: 20.0

arm_sim_driver:
  ros__parameters:
    slider_max_vel: 0.05
    slider_max_accel: 0.1
    shoulder_max_vel: 0.67
    shoulder_max_accel: 2.0
    elbow_max_vel: 0.67
    elbow_max_accel: 2.0
    slider_limits: [-0.25, 0.0]
    shoulder_limits: [-3.14159, 3.14159]
    elbow_limits: [-3.14159, 3.14159]
