keys:
    A: {x: -0.14, y: -0.01}
    S: {x: -0.12, y: -0.01}
    D: {x: -0.10, y: -0.01}
    F: {x: -0.08, y: -0.01}
    G: {x: -0.06, y: -0.01}
    H: {x: -0.04, y: -0.01}
    J: {x: -0.02, y: -0.01}
    K: {x: 0.0, y: -0.01}
    L: {x: 0.02, y: -0.01}
    ';' : {x: 0.04, y: -0.01}
    '''' : {x: 0.06, y: -0.01}
    ENTER: {x: 0.085, y: -0.01}


    Q: {x: -0.145, y: 0.01}
    W: {x: -0.125, y: 0.01}
    E: {x: -0.105, y: 0.01}
    R: {x: -0.085, y: 0.01}
    T: {x: -0.065, y: 0.01}
    Y: {x: -0.045, y: 0.01}
    U: {x: -0.025, y: 0.01}
    I: {x: -0.005, y: 0.01}
    O: {x: 0.015, y: 0.01}
    P: {x: 0.035, y: 0.01}
    '[' : {x: 0.055, y: 0.01}
    ']' : {x: 0.075, y: 0.01}
    '\' : {x: 0.095, y: 0.01}

    Z: {x: -0.13, y: -0.03}
    X: {x: -0.11, y: -0.03}
    C: {x: -0.09, y: -0.03}
    V: {x: -0.07, y: -0.03}
    B: {x: -0.05, y: -0.03}
    N: {x: -0.03, y: -0.03}
    M: {x: -0.01, y: -0.03}
    ',' : {x: 0.01, y: -0.03}
    '.' : {x: 0.03, y: -0.03}
    '/' : {x: 0.05, y: -0.03}

    SPACE: {x: -0.05, y: -0.05}

    '1': {x: -0.155, y: 0.03}
    '2': {x: -0.135, y: 0.03}
    '3': {x: -0.115, y: 0.03}
    '4': {x: -0.095, y: 0.03}
    '5': {x: -0.075, y: 0.03}
    '6': {x: -0.055, y: 0.03}
    '7': {x: -0.035, y: 0.03}
    '8': {x: -0.015, y: 0.03}
    '9': {x: 0.005, y: 0.03}
    '0': {x: 0.025, y: 0.03}
    '-': {x: 0.045, y: 0.03}
    '=': {x: 0.065, y: 0.03}
    BACKSPACE: {x: 0.09, y: 0.03}
    